### ISSUE TITLE
Option to hide the main window title to make the app safe for work

### ISSUE THREAD

**Issue by Chouffy** [efck-chat-keyboard/efck#15]
**Is your feature request related to a problem? Please describe.**
This piece of software is great, thank you for that! I really like it over Windows 11 default emoji picker.
However, the main window has the nice title "EF*CK" … which may be not "safe to work" 😉

**Describe the solution you'd like**
An option to hide or rename the title to something nicer

**Comment by kernc** [comment]
> I really like it over Windows 11 default emoji picker.

# 🥰

-----
The label simply contains the application name to compensate for the missing window title bar. The label contracts _"Emoji Filter/Unicode Chat Keyboard"_, where "Unicode" was later revised into "*" so as to not limit the app scope too prematurely.
Resemblance of any nsfw motifs is purely coincidental.
