### ISSUE TITLE
EFCK Not pasting emojis or putting in clipboard

### ISSUE THREAD

**Issue by kmaba** [efck-chat-keyboard/efck#19]
**Describe the bug**
EFCK Not pasting emojis or putting in clipboard

**To Reproduce**
I do not know how to reproduce this, this error has been happening since 22.10 Kinetic Kudu, both in the Linux binary package and the .deb package

**Expected behavior**
idk

**Versions**
Specify versions:
OS: Ubuntu Linux Lunar Lobster (23.04)
Qt: I think 6
EFCK: [This one](https://github.com/efck-chat-keyboard/efck/actions/runs/4100062349)

**Additional context, screenshots**
After clicking an emoji:
<pre><span style="color:#26A269"><b>dolosarafat@dolosarafat</b></span>:<span style="color:#12488B"><b>~</b></span>$ /home/dolosarafat/.local/share/applications/efck/efck-chat-keyboard
ydotool: notice: ydotoold backend unavailable (may have latency+delay issues)
terminate called after throwing an instance of &apos;std::runtime_error&apos;
  what():  failed to open uinput device
2677	ERROR   	efck.output    	No command applies. Please see above for additional warnings.
<span style="color:#26A269"><b>dolosarafat@dolosarafat</b></span>:<span style="color:#12488B"><b>~</b></span>$ 
</pre>

**Comment by dolosarafat** [comment]
how to configure correctly?

**Comment by kernc** [comment]
I have no idea, I've never used ydotool/Wayland. This looks somewhat relevant: https://github.com/ReimuNotMoe/ydotool/issues/36. Apparently, you need to [ensure <code>ydotool<b>d</b></code> is running](https://github.com/ReimuNotMoe/ydotool#why-a-background-service-is-needed) ...

**Comment by kernc** [comment]
Some more relevant info with non-working clipboard on Wayland in https://github.com/efck-chat-keyboard/efck/issues/22.
